// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtKNzc7jPcup7KqRs6k_lYZ4XeqPLGPZI',
    appId: '1:1015456418369:web:680b1e831682cea1c094c0',
    messagingSenderId: '1015456418369',
    projectId: 'appkhaosat-5b1fa',
    authDomain: 'appkhaosat-5b1fa.firebaseapp.com',
    databaseURL: 'https://appkhaosat-5b1fa-default-rtdb.firebaseio.com',
    storageBucket: 'appkhaosat-5b1fa.appspot.com',
    measurementId: 'G-WY22J04R7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtEsMfx7F94X1F4IVhabUrcOmZSrA3pFg',
    appId: '1:1015456418369:android:d158aa12e06de7d3c094c0',
    messagingSenderId: '1015456418369',
    projectId: 'appkhaosat-5b1fa',
    databaseURL: 'https://appkhaosat-5b1fa-default-rtdb.firebaseio.com',
    storageBucket: 'appkhaosat-5b1fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7yKQ1f5w3VY-hgR2xlXHioW4pORRHOXo',
    appId: '1:1015456418369:ios:ffd805136760cd2fc094c0',
    messagingSenderId: '1015456418369',
    projectId: 'appkhaosat-5b1fa',
    databaseURL: 'https://appkhaosat-5b1fa-default-rtdb.firebaseio.com',
    storageBucket: 'appkhaosat-5b1fa.appspot.com',
    iosClientId: '1015456418369-iubttrbk0rqg8kl7eo8vt4rape4in7s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appkhaosat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7yKQ1f5w3VY-hgR2xlXHioW4pORRHOXo',
    appId: '1:1015456418369:ios:ffd805136760cd2fc094c0',
    messagingSenderId: '1015456418369',
    projectId: 'appkhaosat-5b1fa',
    databaseURL: 'https://appkhaosat-5b1fa-default-rtdb.firebaseio.com',
    storageBucket: 'appkhaosat-5b1fa.appspot.com',
    iosClientId: '1015456418369-iubttrbk0rqg8kl7eo8vt4rape4in7s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appkhaosat',
  );
}
